import http from "node:http";
import { readFile } from "node:fs/promises";
import { join, extname } from "node:path";
import { fileURLToPath } from "node:url";

const root=fileURLToPath(new URL(".",import.meta.url)),publicDir=join(root,"public");

async function loadEnv(){try{const text=await readFile(join(root,".env"),"utf8");for(const line of text.split(/\r?\n/)){const t=line.trim();if(!t||t.startsWith("#"))continue;const i=t.indexOf("=");if(i<0)continue;const k=t.slice(0,i).trim(),v=t.slice(i+1).trim().replace(/^["']|["']$/g,"");if(!process.env[k])process.env[k]=v}}catch{}}
await loadEnv();

const provider=process.env.AI_PROVIDER||"openrouter",model=process.env.AI_MODEL||"google/gemini-2.5-flash";
function providerConfig(){if(provider==="openrouter")return{baseUrl:"https://openrouter.ai/api/v1",apiKey:process.env.OPENROUTER_API_KEY,headers:{"HTTP-Referer":process.env.APP_URL||"http://localhost:3000","X-Title":process.env.APP_NAME||"Personal AI Assistant"}};if(provider==="ollama")return{baseUrl:process.env.AI_BASE_URL||"http://127.0.0.1:11434/v1",apiKey:process.env.AI_API_KEY||"ollama",headers:{}};return{baseUrl:process.env.AI_BASE_URL||"https://api.openai.com/v1",apiKey:process.env.AI_API_KEY,headers:{}}}
function json(res,status,body){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8"});res.end(JSON.stringify(body))}
async function readBody(req){let raw="";for await(const chunk of req)raw+=chunk;if(raw.length>2000000)throw Error("Request is too large.");return JSON.parse(raw||"{}")}
async function chat(messages,selectedModel){const c=providerConfig();if(!c.apiKey&&provider!=="ollama")throw Error("No API key configured. Copy .env.example to .env and add your provider key.");const response=await fetch(c.baseUrl+"/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${c.apiKey}`,"Content-Type":"application/json",...c.headers},body:JSON.stringify({model:selectedModel||model,messages,temperature:.7,stream:false})});const data=await response.json();if(!response.ok)throw Error(data?.error?.message||`Model provider returned HTTP ${response.status}`);return{message:data?.choices?.[0]?.message?.content??"",model:data?.model||selectedModel||model,usage:data?.usage||null}}
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8"};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,"http://localhost");if(req.method==="GET"&&url.pathname==="/api/config")return json(res,200,{provider,model,configured:Boolean(provider==="ollama"||providerConfig().apiKey)});if(req.method==="POST"&&url.pathname==="/api/chat"){const input=await readBody(req);if(!Array.isArray(input.messages)||!input.messages.length)return json(res,400,{error:"messages must be a non-empty array"});const messages=input.messages.filter(m=>m&&["system","user","assistant"].includes(m.role)&&typeof m.content==="string").slice(-40);return json(res,200,await chat(messages,input.model))}const relative=url.pathname==="/"?"index.html":url.pathname.replace(/^\/+ /,"");const filePath=join(publicDir,relative);if(!filePath.startsWith(publicDir))return json(res,403,{error:"Forbidden"});const file=await readFile(filePath);res.writeHead(200,{"Content-Type":mime[extname(filePath)]||"application/octet-stream"});res.end(file)}catch(error){console.error(error);json(res,500,{error:error.message||"Unexpected server error"})}});
const port=Number(process.env.PORT||3000);server.listen(port,()=>console.log(`Personal AI Assistant running at http://localhost:${port}`));
